In [1]:
from sqlalchemy import create_engine, MetaData

url = "escola.db"
engine = create_engine(f"sqlite:///{url}")

In [3]:
md_obj = MetaData()
md_obj.reflect(engine)
md_obj.tables.keys()

dict_keys(['Alunos', 'Disciplinas', 'Professores'])

In [4]:
import pandas as pd
pd.read_sql_table("Alunos", engine)

    ID_Aluno      Nome              Email   Rua_Numero Estado  Nota_Final
0          1   Aluno 1   aluno1@email.com    Rua 1, 10     BA         5.2
1          2   Aluno 2   aluno2@email.com    Rua 2, 20     BA         7.2
2          3   Aluno 3   aluno3@email.com    Rua 3, 30     BA         9.8
3          4   Aluno 4   aluno4@email.com    Rua 4, 40     SP         8.0
4          5   Aluno 5   aluno5@email.com    Rua 5, 50     SP         9.7
5          6   Aluno 6   aluno6@email.com    Rua 6, 60     RJ         9.8
6          7   Aluno 7   aluno7@email.com    Rua 7, 70     RJ         9.0
7          8   Aluno 8   aluno8@email.com    Rua 8, 80     MG         5.2
8          9   Aluno 9   aluno9@email.com    Rua 9, 90     MG         9.9
9         10  Aluno 10  aluno10@email.com  Rua 10, 100     RJ         8.3
10        11  Aluno 11  aluno11@email.com  Rua 11, 110     RJ         7.5
11        12  Aluno 12  aluno12@email.com  Rua 12, 120     MG         8.8
12        13  Aluno 13  aluno13@email.com  Rua 13, 130     SP         7.5
13        14  Aluno 14  aluno14@email.com  Rua 14, 140     BA         7.7
14        15  Aluno 15  aluno15@email.com  Rua 15, 150     BA         6.0
15        16  Aluno 16  aluno16@email.com  Rua 16, 160     RS         5.2
16        17  Aluno 17  aluno17@email.com  Rua 17, 170     MG         8.1
17        18  Aluno 18  aluno18@email.com  Rua 18, 180     RJ         5.6
18        19  Aluno 19  aluno19@email.com  Rua 19, 190     SP         5.7
19        20  Aluno 20  aluno20@email.com  Rua 20, 200     RJ         5.4

In [5]:
import pandas as pd
pd.read_sql_table("Disciplinas", engine)

,ID_Disciplina,Nome,Descricao,Carga_Horaria,ID_Professor
0,1,Disciplina 1,Descrição da Disciplina 1,60,9
1,2,Disciplina 2,Descrição da Disciplina 2,30,2
2,3,Disciplina 3,Descrição da Disciplina 3,45,2
3,4,Disciplina 4,Descrição da Disciplina 4,90,3
4,5,Disciplina 5,Descrição da Disciplina 5,30,15
5,6,Disciplina 6,Descrição da Disciplina 6,90,9
6,7,Disciplina 7,Descrição da Disciplina 7,60,2
7,8,Disciplina 8,Descrição da Disciplina 8,45,3
8,9,Disciplina 9,Descrição da Disciplina 9,60,1
9,10,Disciplina 10,Descrição da Disciplina 10,45,17
10,11,Disciplina 11,Descrição da Disciplina 11,45,6
11,12,Disciplina 12,Descrição da Disciplina 12,30,10
12,13,Disciplina 13,Descrição da Disciplina 13,60,8
13,14,Disciplina 14,Descrição da Disciplina 14,60,7
14,15,Disciplina 15,Descrição da Disciplina 15,30,11
15,16,Disciplina 16,Descrição da Disciplina 16,60,17
16,17,Disciplina 17,Descrição da Disciplina 17,45,1
17,18,Disciplina 18,Descrição da Disciplina 18,60,15
18,19,Disciplina 19,Descrição da Disciplina 19,45,8
19,20,Disciplina 20,Descrição da Disciplina 20,45,15

### Configuração LlamaIndex

In [6]:
from dotenv import load_dotenv
import os

_ = load_dotenv()
GROQ_API = os.environ.get("GROQ_API_KEY")

In [7]:
model = "llama-3.3-70b-versatile"
model_hf_emb = "BAAI/bge-m3"

In [8]:
from llama_index.core import Settings
from llama_index.llms.groq import Groq
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

Settings.llm = Groq(model=model, api_key=GROQ_API)
Settings.embed_model = HuggingFaceEmbedding(model_name=model_hf_emb)

### Configuração BD no Modelo

In [9]:
from llama_index.core import SQLDatabase
from llama_index.core.objects import SQLTableNodeMapping

sql_db = SQLDatabase(engine)
table_node_map = SQLTableNodeMapping(sql_db)

In [11]:
from llama_index.core.objects import SQLTableSchema

table_schema_objs = []
for table_name in md_obj.tables.keys():
    table_schema_objs.append(SQLTableSchema(table_name=table_name))

In [12]:
from llama_index.core.objects import ObjectIndex
from llama_index.core import VectorStoreIndex

obj_index = ObjectIndex.from_objects(
    table_schema_objs,
    table_node_map,
    VectorStoreIndex
)

In [13]:
obj_retriever = obj_index.as_retriever(similarity_top_k=1)

### Testando a Primeira Consulta

In [14]:
from llama_index.core.indices.struct_store.sql_query import SQLTableRetrieverQueryEngine

query_engine = SQLTableRetrieverQueryEngine(
    sql_db,
    obj_retriever
)

In [15]:
response = query_engine.query("Quais estados mais frequentes na tabela Alunos?")

In [16]:
print(response)

Os estados mais frequentes na tabela Alunos são RJ, com 6 ocorrências, seguido por BA, com 5 ocorrências, e SP e MG, com 4 ocorrências cada. O estado RS é o menos frequente, com apenas 1 ocorrência.

In [17]:
response.metadata

{'565c2437-1213-4e83-bddb-f1906397ad68': {'sql_query': 'SELECT Estado, COUNT(ID_Aluno) AS Frequencia FROM Alunos GROUP BY Estado ORDER BY Frequencia DESC',
  'result': [('RJ', 6), ('BA', 5), ('SP', 4), ('MG', 4), ('RS', 1)],
  'col_keys': ['Estado', 'Frequencia']},
 'sql_query': 'SELECT Estado, COUNT(ID_Aluno) AS Frequencia FROM Alunos GROUP BY Estado ORDER BY Frequencia DESC',
 'result': [('RJ', 6), ('BA', 5), ('SP', 4), ('MG', 4), ('RS', 1)],
 'col_keys': ['Estado', 'Frequencia']}

In [18]:
response = query_engine.query("Quais professores residem na cidade de São Paulo?")

In [19]:
print(response)

Os professores que residem na cidade de São Paulo são:

- Professor 7, que mora na Rua 7, no Bairro 7.
- Professor 8, que mora na Rua 8, no Bairro 8.
- Professor 10, que mora na Rua 10, no Bairro 10.
- Professor 11, que mora na Rua 11, no Bairro 11.
- Professor 20, que mora na Rua 20, no Bairro 20.

In [20]:
response.metadata

{'9a987c45-87ce-4497-93e0-0075b39b34db': {'sql_query': "SELECT Nome, Rua, Bairro FROM Professores WHERE Cidade = 'São Paulo'",
  'result': [('Professor 7', 'Rua 7', 'Bairro 7'),
   ('Professor 8', 'Rua 8', 'Bairro 8'),
   ('Professor 10', 'Rua 10', 'Bairro 10'),
   ('Professor 11', 'Rua 11', 'Bairro 11'),
   ('Professor 20', 'Rua 20', 'Bairro 20')],
  'col_keys': ['Nome', 'Rua', 'Bairro']},
 'sql_query': "SELECT Nome, Rua, Bairro FROM Professores WHERE Cidade = 'São Paulo'",
 'result': [('Professor 7', 'Rua 7', 'Bairro 7'),
  ('Professor 8', 'Rua 8', 'Bairro 8'),
  ('Professor 10', 'Rua 10', 'Bairro 10'),
  ('Professor 11', 'Rua 11', 'Bairro 11'),
  ('Professor 20', 'Rua 20', 'Bairro 20')],
 'col_keys': ['Nome', 'Rua', 'Bairro']}

### Melhorando o Contexto do Modelo

In [22]:
def generate_description_table(table_name, df_amostra):
    prompt = f"""
    Analise a amostra da tabela '{table_name}' abaixo e forneça uma
    curta e breve descrição do conteúdo dessa tabela.
    Informe até o máximo de 5 valores únicos de cada coluna.
    
    Amostra da tabela:
    {df_amostra}
    
    Descrição:
    
    """
    llm = Groq(model=model, api_key=GROQ_API)
    response = llm.complete(prompt=prompt)
    return response.text

In [23]:
names_tables = md_obj.tables.keys()
dict_tables = {}
for name_table in names_tables:
    df = pd.read_sql_table(name_table, engine)
    df_amostra = df.head(5).to_string()
    
    descricao = generate_description_table(name_table, df_amostra)
    dict_tables[name_table] = descricao
    print(f"Tabela: {name_table}\nDescrição: {descricao}")
    print("-"*15)

Tabela: Alunos
Descrição: A tabela 'Alunos' contém informações sobre os alunos de uma instituição de ensino. As colunas incluem:

- **ID_Aluno**: Identificador único do aluno, com valores únicos como 1, 2, 3, 4 e 5.
- **Nome**: Nome do aluno, com valores únicos como Aluno 1, Aluno 2, Aluno 3, Aluno 4 e Aluno 5.
- **Email**: Endereço de e-mail do aluno, com valores únicos como aluno1@email.com, aluno2@email.com, aluno3@email.com, aluno4@email.com e aluno5@email.com.
- **Rua_Numero**: Endereço do aluno, com valores únicos como Rua 1, 10, Rua 2, 20, Rua 3, 30, Rua 4, 40 e Rua 5, 50.
- **Estado**: Estado onde o aluno reside, com valores únicos como BA (Bahia) e SP (São Paulo).
- **Nota_Final**: Nota final do aluno, com valores únicos como 5.2, 7.2, 9.8, 8.0 e 9.7.

Essa tabela parece conter informações básicas sobre os alunos, incluindo seus dados de contato, endereço e desempenho acadêmico.
---------------
Tabela: Disciplinas
Descrição: A tabela 'Disciplinas' contém informações sobre disciplinas acadêmicas. Abaixo está uma breve descrição do conteúdo de cada coluna, juntamente com até 5 valores únicos encontrados em cada uma delas:

- **ID_Disciplina**: Identificador único para cada disciplina. Valores únicos: 1, 2, 3, 4, 5
- **Nome**: Nome da disciplina. Valores únicos: Disciplina 1, Disciplina 2, Disciplina 3, Disciplina 4, Disciplina 5
- **Descricao**: Descrição detalhada da disciplina. Valores únicos: Descrição da Disciplina 1, Descrição da Disciplina 2, Descrição da Disciplina 3, Descrição da Disciplina 4, Descrição da Disciplina 5
- **Carga_Horaria**: Número de horas dedicadas à disciplina. Valores únicos: 60, 30, 45, 90
- **ID_Professor**: Identificador do professor responsável pela disciplina. Valores únicos: 9, 2, 3, 15

Essa tabela parece ser utilizada para gerenciar informações sobre disciplinas em um contexto acadêmico, como em uma instituição de ensino. Ela relaciona cada disciplina com seu professor e fornece detalhes sobre a carga horária e descrição da disciplina.
---------------
Tabela: Professores
Descrição: A tabela 'Professores' contém informações sobre professores de uma escola. As colunas incluem:

- **ID_Professor**: identificador único do professor (valores únicos: 1, 2, 3, 4, 5)
- **Nome**: nome do professor (valores únicos: Professor 1, Professor 2, Professor 3, Professor 4, Professor 5)
- **Especialidade**: área de especialização do professor (valores únicos: Física, Matemática, História)
- **Data_Admissao**: data em que o professor foi admitido (valores únicos: 2020-11-08, 2024-02-17, 2022-06-28, 2016-10-21, 2015-05-25)
- **Telefone**: número de telefone do professor (valores únicos: 11999990001, 11999990002, 11999990003, 11999990004, 11999990005)
- **Email**: endereço de e-mail do professor (valores únicos: prof1@escola.com, prof2@escola.com, prof3@escola.com, prof4@escola.com, prof5@escola.com)
- **Rua**: rua onde o professor reside (valores únicos: Rua 1, Rua 2, Rua 3, Rua 4, Rua 5)
- **Bairro**: bairro onde o professor reside (valores únicos: Bairro 1, Bairro 2, Bairro 3, Bairro 4, Bairro 5)
- **Cidade**: cidade onde o professor reside (valores únicos: Rio de Janeiro, Salvador)

Essa tabela parece conter informações básicas sobre os professores, incluindo suas especialidades, contatos e endereços.
---------------

In [24]:
table_schema_objs = [
    SQLTableSchema(
        table_name=table_name,
        context_str=dict_tables[table_name]
    )
    for table_name in names_tables
]

In [25]:
table_schema_objs

[SQLTableSchema(table_name='Alunos', context_str="A tabela 'Alunos' contém informações sobre os alunos de uma instituição de ensino. As colunas incluem:\n\n- **ID_Aluno**: Identificador único do aluno, com valores únicos como 1, 2, 3, 4 e 5.\n- **Nome**: Nome do aluno, com valores únicos como Aluno 1, Aluno 2, Aluno 3, Aluno 4 e Aluno 5.\n- **Email**: Endereço de e-mail do aluno, com valores únicos como aluno1@email.com, aluno2@email.com, aluno3@email.com, aluno4@email.com e aluno5@email.com.\n- **Rua_Numero**: Endereço do aluno, com valores únicos como Rua 1, 10, Rua 2, 20, Rua 3, 30, Rua 4, 40 e Rua 5, 50.\n- **Estado**: Estado onde o aluno reside, com valores únicos como BA (Bahia) e SP (São Paulo).\n- **Nota_Final**: Nota final do aluno, com valores únicos como 5.2, 7.2, 9.8, 8.0 e 9.7.\n\nEssa tabela parece conter informações básicas sobre os alunos, incluindo seus dados de contato, endereço e desempenho acadêmico."),
 SQLTableSchema(table_name='Disciplinas', context_str="A tabela 'Disciplinas' contém informações sobre disciplinas acadêmicas. Abaixo está uma breve descrição do conteúdo de cada coluna, juntamente com até 5 valores únicos encontrados em cada uma delas:\n\n- **ID_Disciplina**: Identificador único para cada disciplina. Valores únicos: 1, 2, 3, 4, 5\n- **Nome**: Nome da disciplina. Valores únicos: Disciplina 1, Disciplina 2, Disciplina 3, Disciplina 4, Disciplina 5\n- **Descricao**: Descrição detalhada da disciplina. Valores únicos: Descrição da Disciplina 1, Descrição da Disciplina 2, Descrição da Disciplina 3, Descrição da Disciplina 4, Descrição da Disciplina 5\n- **Carga_Horaria**: Número de horas dedicadas à disciplina. Valores únicos: 60, 30, 45, 90\n- **ID_Professor**: Identificador do professor responsável pela disciplina. Valores únicos: 9, 2, 3, 15\n\nEssa tabela parece ser utilizada para gerenciar informações sobre disciplinas em um contexto acadêmico, como em uma instituição de ensino. Ela relaciona cada disciplina com seu professor e fornece detalhes sobre a carga horária e descrição da disciplina."),
 SQLTableSchema(table_name='Professores', context_str="A tabela 'Professores' contém informações sobre professores de uma escola. As colunas incluem:\n\n- **ID_Professor**: identificador único do professor (valores únicos: 1, 2, 3, 4, 5)\n- **Nome**: nome do professor (valores únicos: Professor 1, Professor 2, Professor 3, Professor 4, Professor 5)\n- **Especialidade**: área de especialização do professor (valores únicos: Física, Matemática, História)\n- **Data_Admissao**: data em que o professor foi admitido (valores únicos: 2020-11-08, 2024-02-17, 2022-06-28, 2016-10-21, 2015-05-25)\n- **Telefone**: número de telefone do professor (valores únicos: 11999990001, 11999990002, 11999990003, 11999990004, 11999990005)\n- **Email**: endereço de e-mail do professor (valores únicos: prof1@escola.com, prof2@escola.com, prof3@escola.com, prof4@escola.com, prof5@escola.com)\n- **Rua**: rua onde o professor reside (valores únicos: Rua 1, Rua 2, Rua 3, Rua 4, Rua 5)\n- **Bairro**: bairro onde o professor reside (valores únicos: Bairro 1, Bairro 2, Bairro 3, Bairro 4, Bairro 5)\n- **Cidade**: cidade onde o professor reside (valores únicos: Rio de Janeiro, Salvador)\n\nEssa tabela parece conter informações básicas sobre os professores, incluindo suas especialidades, contatos e endereços.")]

In [26]:
obj_index = ObjectIndex.from_objects(
    table_schema_objs,
    table_node_map,
    VectorStoreIndex
)
obj_retriever = obj_index.as_retriever(similarity_top_k=1)

In [27]:
query_engine_2 = SQLTableRetrieverQueryEngine(sql_db, obj_retriever)
response = query_engine_2.query("Quantos professores de Física temos?")

In [28]:
print(response)

Temos 6 professores de Física.

In [29]:
response.metadata

{'33b32649-52a7-46e3-b5af-4a3643ee1ddd': {'sql_query': "SELECT COUNT(ID_Professor) FROM Professores WHERE Especialidade = 'Física'",
  'result': [(6,)],
  'col_keys': ['COUNT(ID_Professor)']},
 'sql_query': "SELECT COUNT(ID_Professor) FROM Professores WHERE Especialidade = 'Física'",
 'result': [(6,)],
 'col_keys': ['COUNT(ID_Professor)']}

In [30]:
response = query_engine_2.query("Quantos professores de Física que residem em São Paulo?")

In [31]:
print(response)

Existem 2 professores de Física que residem em São Paulo.

In [32]:
response.metadata

{'2c82b46d-331f-4534-b78b-80bb9a0583a6': {'sql_query': "SELECT COUNT(P.ID_Professor) FROM Professores P WHERE P.Especialidade = 'Física' AND P.Cidade = 'São Paulo'",
  'result': [(2,)],
  'col_keys': ['COUNT(P.ID_Professor)']},
 'sql_query': "SELECT COUNT(P.ID_Professor) FROM Professores P WHERE P.Especialidade = 'Física' AND P.Cidade = 'São Paulo'",
 'result': [(2,)],
 'col_keys': ['COUNT(P.ID_Professor)']}

In [36]:
from huggingface_hub import hf_hub_download

model_path = hf_hub_download(repo_id="BAAI/bge-m3", filename="pytorch_model.bin")
print(model_path)

C:\Users\rodri\.cache\huggingface\hub\models--BAAI--bge-m3\snapshots\5617a9f61b028005a4858fdac845db406aefb181\pytorch_model.bin